<a href="https://colab.research.google.com/github/paola4280/deep-learning-challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import numpy as np

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=["EIN", "NAME"])

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE

application_type_counts = application_df["APPLICATION_TYPE"].value_counts()


top_n = 10  # Adjust based on how many categories you want to keep
application_types_to_keep = application_type_counts.nlargest(top_n).index

application_df["APPLICATION_TYPE"] = application_df["APPLICATION_TYPE"].apply(
    lambda x: x if x in application_types_to_keep else "Other"
)

application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
Other       54
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

application_type_counts = application_df["APPLICATION_TYPE"].value_counts()

cutoff_value = 20
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

application_df["APPLICATION_TYPE"] = application_df["APPLICATION_TYPE"].replace(application_types_to_replace, "Other")

application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
Other       54
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
classification_counts = application_df["CLASSIFICATION"].value_counts()

cutoff_value = 20
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

application_df["CLASSIFICATION"] = application_df["CLASSIFICATION"].replace(classifications_to_replace, "Other")

application_df["CLASSIFICATION"].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
Other      207
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
Name: count, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
# Look at CLASSIFICATION value counts greater than 1
classification_counts = application_df["CLASSIFICATION"].value_counts()

# Filter classifications with counts greater than 1
classifications_greater_than_one = classification_counts[classification_counts > 1]
print(classifications_greater_than_one)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
Other      207
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
Other      207
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df = pd.get_dummies(application_df, drop_first=True)

application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,ORGANIZATION_Trust,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,108590,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,1,6692,1,False,False,False,True,False,False,False,...,True,False,True,False,False,False,False,False,False,False
4,1,142590,1,False,False,False,True,False,False,False,...,True,False,False,True,False,False,False,False,False,False

In [ ]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(columns=["IS_SUCCESSFUL"]).values

print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)
X_train = np.asarray(X_train).astype('float32')
X_test = np.asarray(X_test).astype('float32')
y_train = np.asarray(y_train).astype('float32')  # Use 'int32' if labels are integers
y_test = np.asarray(y_test).astype('float32')   # Use 'int32' if labels are integers

Features shape: (34299, 54)
Target shape: (34299,)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=X_train.shape[1]))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_44 (Dense)                     │ (None, 80)                  │           4,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_45 (Dense)                     │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_46 (Dense)                     │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,861 (26.80 KB)

 Trainable params: 6,861 (26.80 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
#  YOUR CODE GOES HERE
from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate=0.3)
nn.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [ ]:
# Train the model
#  YOUR CODE GOES HERE
history = nn.fit(X_train, y_train,
                 epochs=100,
                 batch_size=32,
                 validation_split=0.2,
                 verbose=1)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5120 - loss: 0.6970 - val_accuracy: 0.5444 - val_loss: 0.6898
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5133 - loss: 0.6966 - val_accuracy: 0.5444 - val_loss: 0.6893
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.5130 - loss: 0.6961 - val_accuracy: 0.4556 - val_loss: 0.7012
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5156 - loss: 0.6976 - val_accuracy: 0.5444 - val_loss: 0.6921
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5139 - loss: 0.6950 - val_accuracy: 0.4556 - val_loss: 0.7047
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.5133 - loss: 0.6975 - val_accuracy: 0.4556 - val_loss: 0.7015
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5177 - loss: 0.6992 - val_accuracy: 0.5444 - val_loss: 0.6902
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.5068 - loss: 0.6974 - val_accuracy: 0.5444 - val_loss: 0.6925
Epoch 9/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.5121 - loss: 0.6952 - val_accuracy: 0.5444 - val_loss: 0.6939
Epoch 10/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.5126 - loss: 0.6973 - val_accuracy: 0.5444 - val_loss: 0.7073
Epoch 11/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.5103 - loss: 0.6976 - val_accuracy: 0.5444 - val_loss: 0.6914
Epoch 12/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5107 - loss: 0.6979 - val_accuracy: 0.4556 - val_loss: 0.7000
Epoch 13/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5151 - loss: 0.6962 - val_accuracy: 0.5444 - val_loss: 0.7115
Epoch 14/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5162 - loss: 0.6995 - val_accuracy: 0.5444 - val_loss: 0.6903
Epoch 15/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5126 - loss: 0.6962 - val_accuracy: 0.4556 - val_loss: 0.7077
Epoch 16/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5047 - loss: 0.7004 - val_accuracy: 0.5444 - val_loss: 0.6897
Epoch 17/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5129 - loss: 0.6983 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 18/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5144 - loss: 0.6971 - val_accuracy: 0.5444 - val_loss: 0.6893
Epoch 19/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5119 - loss: 0.6962 - val_accuracy: 0.4556 - val_loss: 0.6979
Epoch 20/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5116 - loss: 0.6974 - val_accuracy: 0.5444 - val_loss: 0.6914
Epoch 21/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5132 - loss: 0.6970 - val_accuracy: 0.4556 - val_loss: 0.6990
Epoch 22/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5144 - loss: 0.6984 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 23/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5207 - loss: 0.6954 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 24/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5118 - loss: 0.6970 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 25/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5138 - loss: 0.6962 - val_accuracy: 0.5444 - val_loss: 0.7031
Epoch 26/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5149 - loss: 0.6973 - val_accuracy: 0.4556 - val_loss: 0.6942
Epoch 27/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5192 - loss: 0.6960 - val_accuracy: 0.4556 - val_loss: 0.7084
Epoch 28/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5073 - loss: 0.7016 - val_accuracy: 0.5444 - val_loss: 0.6932
Epoch 29/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5160 - loss: 0.6963 - val_accuracy: 0.4556 - val_loss: 0.6997
Epoch 30/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5084 - loss: 0.6968 - val_accuracy: 0.5444 - val_loss: 0.6896
Epoch 31/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5171 - loss: 0.6980 - val_accuracy: 0.5444 - val_loss: 0.6893
Epoch 32/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5258 - loss: 0.6949 - val_accuracy: 0.5444 - val_loss: 0.6893
Epoch 33/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5082 - loss: 0.6983 - val_accuracy: 0.5444 - val_loss: 0.6920
Epoch 34/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5076 - loss: 0.6980 - val_accuracy: 0.5444 - val_loss: 0.6899
Epoch 35/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5136 - loss: 0.6952 - val_accuracy: 0.4556 - val_loss: 0.6954
Epoch 36/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5069 - loss: 0.6976 - val_accuracy: 0.4556 - val_loss: 0.6970
Epoch 37/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5156 - loss: 0.6988 - val_accuracy: 0.5444 - val_loss: 0.6909
Epoch 38/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5128 - loss: 0.6959 - val_accuracy: 0.4556 - val_loss: 0.6993
Epoch 39/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5180 - loss: 0.6962 - val_accuracy: 0.5444 - val_loss: 0.7224
Epoch 40/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5078 - loss: 0.7027 - val_accuracy: 0.4556 - val_loss: 0.7232
Epoch 41/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5111 - loss: 0.6973 - val_accuracy: 0.4556 - val_loss: 0.6950
Epoch 42/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5029 - loss: 0.6976 - val_accuracy: 0.5444 - val_loss: 0.6914
Epoch 43/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5131 - loss: 0.6973 - val_accuracy: 0.5444 - val_loss: 0.6895
Epoch 44/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5136 - loss: 0.6986 - val_accuracy: 0.4556 - val_loss: 0.6967
Epoch 45/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5053 - loss: 0.6987 - val_accuracy: 0.5444 - val_loss: 0.6949
Epoch 46/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5166 - loss: 0.6984 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 47/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5136 - loss: 0.6994 - val_accuracy: 0.4556 - val_loss: 0.7351
Epoch 48/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5214 - loss: 0.6971 - val_accuracy: 0.5444 - val_loss: 0.6896
Epoch 49/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5097 - loss: 0.6982 - val_accuracy: 0.5444 - val_loss: 0.6910
Epoch 50/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5100 - loss: 0.6975 - val_accuracy: 0.5444 - val_loss: 0.6927
Epoch 51/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5168 - loss: 0.6950 - val_accuracy: 0.5444 - val_loss: 0.6910
Epoch 52/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5205 - loss: 0.6956 - val_accuracy: 0.4556 - val_loss: 0.7922
Epoch 53/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.4983 - loss: 0.7051 - val_accuracy: 0.4556 - val_loss: 0.6951
Epoch 54/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5102 - loss: 0.6991 - val_accuracy: 0.5444 - val_loss: 0.6902
Epoch 55/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5157 - loss: 0.6958 - val_accuracy: 0.5444 - val_loss: 0.6895
Epoch 56/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5229 - loss: 0.6961 - val_accuracy: 0.5444 - val_loss: 0.6931
Epoch 57/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5216 - loss: 0.6959 - val_accuracy: 0.4556 - val_loss: 0.7521
Epoch 58/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5162 - loss: 0.6973 - val_accuracy: 0.4556 - val_loss: 0.6981
Epoch 59/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5078 - loss: 0.6974 - val_accuracy: 0.4556 - val_loss: 0.6946
Epoch 60/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5126 - loss: 0.6998 - val_accuracy: 0.5444 - val_loss: 0.6928
Epoch 61/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5190 - loss: 0.6963 - val_accuracy: 0.4556 - val_loss: 0.6977
Epoch 62/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5085 - loss: 0.6997 - val_accuracy: 0.5444 - val_loss: 0.7136
Epoch 63/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5029 - loss: 0.7001 - val_accuracy: 0.5444 - val_loss: 0.7078
Epoch 64/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5115 - loss: 0.6973 - val_accuracy: 0.5444 - val_loss: 0.6910
Epoch 65/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5168 - loss: 0.6962 - val_accuracy: 0.4556 - val_loss: 0.7262
Epoch 66/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5092 - loss: 0.6988 - val_accuracy: 0.4556 - val_loss: 0.7240
Epoch 67/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5118 - loss: 0.6964 - val_accuracy: 0.4556 - val_loss: 0.7037
Epoch 68/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5129 - loss: 0.6972 - val_accuracy: 0.5444 - val_loss: 0.6928
Epoch 69/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5191 - loss: 0.6967 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 70/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5183 - loss: 0.6955 - val_accuracy: 0.4556 - val_loss: 0.7361
Epoch 71/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5180 - loss: 0.6985 - val_accuracy: 0.4556 - val_loss: 0.7047
Epoch 72/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5158 - loss: 0.6956 - val_accuracy: 0.5444 - val_loss: 0.6967
Epoch 73/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5129 - loss: 0.6969 - val_accuracy: 0.5444 - val_loss: 0.6894
Epoch 74/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5132 - loss: 0.6960 - val_accuracy: 0.4556 - val_loss: 0.6949
Epoch 75/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5136 - loss: 0.6958 - val_accuracy: 0.5444 - val_loss: 0.7138
Epoch 76/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5111 - loss: 0.6962 - val_accuracy: 0.4556 - val_loss: 0.6938
Epoch 77/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5115 - loss: 0.6966 - val_accuracy: 0.5444 - val_loss: 0.6893
Epoch 78/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5083 - loss: 0.6976 - val_accuracy: 0.4556 - val_loss: 0.7212
Epoch 79/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5120 - loss: 0.6978 - val_accuracy: 0.5444 - val_loss: 0.6894
Epoch 80/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5190 - loss: 0.6964 - val_accuracy: 0.4556 - val_loss: 0.6946
Epoch 81/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5142 - loss: 0.6963 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 82/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5129 - loss: 0.6962 - val_accuracy: 0.4556 - val_loss: 0.6977
Epoch 83/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5089 - loss: 0.6983 - val_accuracy: 0.5444 - val_loss: 0.6897
Epoch 84/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5220 - loss: 0.6944 - val_accuracy: 0.5444 - val_loss: 0.6893
Epoch 85/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5090 - loss: 0.6985 - val_accuracy: 0.5444 - val_loss: 0.6905
Epoch 86/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5097 - loss: 0.6998 - val_accuracy: 0.4556 - val_loss: 0.7164
Epoch 87/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5151 - loss: 0.6952 - val_accuracy: 0.4556 - val_loss: 0.6942
Epoch 88/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5113 - loss: 0.6983 - val_accuracy: 0.4556 - val_loss: 0.6932
Epoch 89/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5096 - loss: 0.6964 - val_accuracy: 0.5444 - val_loss: 0.6931
Epoch 90/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5058 - loss: 0.7009 - val_accuracy: 0.5444 - val_loss: 0.6897
Epoch 91/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5124 - loss: 0.6973 - val_accuracy: 0.4556 - val_loss: 0.6980
Epoch 92/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5039 - loss: 0.6966 - val_accuracy: 0.5444 - val_loss: 0.6894
Epoch 93/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5132 - loss: 0.6961 - val_accuracy: 0.5444 - val_loss: 0.6980
Epoch 94/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5192 - loss: 0.6969 - val_accuracy: 0.4556 - val_loss: 0.6980
Epoch 95/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4955 - loss: 0.6995 - val_accuracy: 0.5444 - val_loss: 0.6892
Epoch 96/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5170 - loss: 0.6966 - val_accuracy: 0.5444 - val_loss: 0.6904
Epoch 97/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5196 - loss: 0.6950 - val_accuracy: 0.4556 - val_loss: 0.7215
Epoch 98/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5041 - loss: 0.6994 - val_accuracy: 0.4556 - val_loss: 0.6981
Epoch 99/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5170 - loss: 0.6984 - val_accuracy: 0.4556 - val_loss: 0.7112
Epoch 100/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5019 - loss: 0.6983 - val_accuracy: 0.5444 - val_loss: 0.6895

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 2ms/step - accuracy: 0.4901 - loss: 0.7016
Loss: 0.7016115188598633, Accuracy: 0.4901457726955414

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("trained_model.h5")
print("Model saved successfully!")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model saved successfully!

In [ ]:
import os
print(os.listdir())

['.config', 'trained_model.h5', 'sample_data']

In [ ]:
from google.colab import files
files.download('trained_model.h5')